version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    exclusions:
      - .git/**
      - README.md
hooks:
  ApplicationStop:
    - location: app/scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: app/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: app/scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: app/scripts/validate_service.sh
      timeout: 300
      runas: root
