version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running pre-build scripts...

  build:
    commands:
      - echo Build started on `date`
      - npm run build

artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*' # Example of excluding files